<?php
/**
 * Addon: Guesty Direct Checkout & Inquiry System
 * Captures the redirect from Unit Pages, builds a dynamic quote checkout page, 
 * and pushes Guest details and Reservations directly into Guesty via the Open API.
 */

if (!defined('ABSPATH')) {
    exit;
}

class Guesty_ALC_Checkout_System {

    public function __construct() {
        // Register URL rewrites and query vars
        add_action('init', [$this, 'add_rewrite_rules']);
        add_filter('query_vars', [$this, 'add_query_vars']);
        add_action('template_redirect', [$this, 'render_checkout_page']);

        // Admin Settings
        add_action('admin_init', [$this, 'register_settings']);
        add_action('admin_footer', [$this, 'inject_admin_tab']);

        // AJAX Form Handlers
        add_action('wp_ajax_guesty_submit_checkout', [$this, 'ajax_submit_checkout']);
        add_action('wp_ajax_nopriv_guesty_submit_checkout', [$this, 'ajax_submit_checkout']);
    }

    public function register_settings() {
        register_setting('guesty-settings-group', 'guesty_checkout_mode');
        register_setting('guesty-settings-group', 'guesty_checkout_success_url', 'sanitize_url');
        register_setting('guesty-settings-group', 'guesty_checkout_terms_url', 'sanitize_url');
    }

    public function add_rewrite_rules() {
        // Intercepts the URL generated by the Unit Pages Book Button: /checkout/LISTING_ID/checkout
        add_rewrite_rule('^checkout/([^/]+)/checkout/?$', 'index.php?guesty_checkout=$matches[1]', 'top');
        // Fallback for simple ID mapping
        add_rewrite_rule('^checkout/([^/]+)/?$', 'index.php?guesty_checkout=$matches[1]', 'top');
    }

    public function add_query_vars($vars) {$vars[] = 'guesty_checkout';
        return $vars;
    }

    /**
     * Injects the Settings tab into the existing Guesty Admin Menu via JavaScript
     */
    public function inject_admin_tab() {
        $screen = get_current_screen();
        if (strpos($screen->id, 'guesty-api-settings') === false) return;
        ?>
        <div id="gvs-panel-checkout" class="gvs-panel" style="display: none; background: #fff; padding: 25px; border: 1px solid #ccd0d4; border-radius: 8px;">
            <div style="display:flex; justify-content:space-between; align-items:center; margin-bottom:15px;">
                <h3 style="margin:0;">Direct Checkout & Inquiries</h3>
                <?php submit_button('Save Checkout Settings', 'primary', 'submit', false); ?>
            </div>
            <p class="description" style="margin-top:-5px; margin-bottom: 20px;">Configure how guest submissions are handled and pushed into your Guesty dashboard.</p>
            
            <table class="form-table">
                <tr valign="top">
                    <th scope="row">Submission Mode</th>
                    <td>
                        <select name="guesty_checkout_mode" style="width: 350px;">
                            <option value="inquiry" <?php selected(get_option('guesty_checkout_mode', 'inquiry'), 'inquiry'); ?>>Inquiry Only (Does not block calendar)</option>
                            <option value="unconfirmed" <?php selected(get_option('guesty_checkout_mode', 'inquiry'), 'unconfirmed'); ?>>Request to Book (Unconfirmed / Awaiting Payment)</option>
                            <option value="confirmed" <?php selected(get_option('guesty_checkout_mode', 'inquiry'), 'confirmed'); ?>>Instant Booking (Confirmed without Payment)</option>
                        </select>
                        <p class="description"><strong>Note:</strong> If you select "Request to Book", the reservation will be created in Guesty so you can automatically trigger your Guesty Auto-Message containing the native payment link!</p>
                    </td>
                </tr>
                <tr valign="top">
                    <th scope="row">Success Redirect URL</th>
                    <td>
                        <input type="url" name="guesty_checkout_success_url" value="<?php echo esc_url(get_option('guesty_checkout_success_url', home_url('/'))); ?>" style="width: 350px;" placeholder="https://..." />
                        <p class="description">Where should the guest be redirected after a successful submission?</p>
                    </td>
                </tr>
                <tr valign="top">
                    <th scope="row">Terms & Conditions URL</th>
                    <td>
                        <input type="url" name="guesty_checkout_terms_url" value="<?php echo esc_url(get_option('guesty_checkout_terms_url', '')); ?>" style="width: 350px;" placeholder="https://..." />
                        <p class="description">Provide the link to your booking terms. If left blank, the checkbox will not require a link.</p>
                    </td>
                </tr>
            </table>
            <div style="margin-top:25px; display: flex; justify-content: flex-end;"><?php submit_button('Save Checkout Settings', 'primary', 'submit', false); ?></div>
        </div>

        <script>
            document.addEventListener('DOMContentLoaded', () => {
                const navBar = document.querySelector('.gvs-nav-tab')?.parentElement;
                if (!navBar) return;
                
                const btn = document.createElement('button');
                btn.type = 'button';
                btn.id = 'gvs-tab-checkout';
                btn.className = 'button gvs-nav-tab';
                btn.innerText = 'Checkout System';
                btn.style.backgroundColor = '#fdf2f8';
                btn.style.borderColor = '#c084fc';
                btn.style.color = '#9333ea';
                btn.style.fontWeight = 'bold';
                btn.onclick = () => gvsShowPanel('checkout');
                
                // Insert before the Action Tabs (Sync buttons)
                const actionTab = navBar.querySelector('form');
                if(actionTab) { navBar.insertBefore(btn, actionTab); } else { navBar.appendChild(btn); }

                const panel = document.getElementById('gvs-panel-checkout');
                const form = document.getElementById('gvs-options-form');
                if(form && panel) {
                    form.appendChild(panel);
                }
            });
        </script>
        <?php
    }

    private function get_access_token() {
        $token = get_transient('guesty_access_token');
        if ($token) return$token;
        $client_id = get_option('guesty_client_id');$client_secret = get_option('guesty_client_secret');
        if (!$client_id \vert{}\vert{} !$client_secret) return false;

        $response = wp_remote_post('https://open-api.guesty.com/oauth2/token', [
            'headers' => [ 'Accept' => 'application/json', 'Content-Type' => 'application/x-www-form-urlencoded' ],
            'body' => [ 'grant_type' => 'client_credentials', 'client_id' => $client_id, 'client_secret' =>$client_secret ]
        ]);
        if (is_wp_error($response) \vert{}\vert{} wp_remote_retrieve_response_code($response) != 200) return false;
        $body = json_decode(wp_remote_retrieve_body($response), true);
        if (is_array($body) && isset($body['access_token'])) {
            set_transient('guesty_access_token', $body['access_token'], 23 * HOUR_IN_SECONDS);
            return $body['access_token'];
        }
        return false;
    }

    public function ajax_submit_checkout() {
        if (!isset($_POST['nonce']) \vert{}\vert{} !wp_verify_nonce($_POST['nonce'], 'guesty_checkout_nonce')) {
            wp_send_json_error(['message' => 'Unauthorized request']);
        }

        $unit_id = sanitize_text_field($_POST['unit_id'] ?? '');
        $check_in = sanitize_text_field($_POST['check_in'] ?? '');
        $check_out = sanitize_text_field($_POST['check_out'] ?? '');
        $guests = (int)($_POST['guests'] ?? 1);
        $coupon = sanitize_text_field($_POST['coupon'] ?? '');
        
        $fname = sanitize_text_field($_POST['first_name'] ?? '');
        $lname = sanitize_text_field($_POST['last_name'] ?? '');
        $email = sanitize_email($_POST['email'] ?? '');
        $phone = sanitize_text_field($_POST['phone'] ?? '');
        $message = sanitize_textarea_field($_POST['message'] ?? '');

        if (empty($fname) || empty($lname) \vert{}\vert{} empty($email)) {
            wp_send_json_error(['message' => 'Please fill in all required guest details.']);
        }

        $token =$this->get_access_token();
        if (!$token) wp_send_json_error(['message' => 'System authentication failure. Please contact support.']);

        $mode = get_option('guesty_checkout_mode', 'inquiry');

        // Prepare Reservation Payload
        $payload = [
            'listingId' => $unit_id,
            'checkInDate' => $check_in,
            'checkOutDate' => $check_out,
            'guestsCount' => $guests,
            'status' => $mode, 
            'source' => 'website',
            'guest' => [
                'firstName' => $fname,
                'lastName' => $lname,
                'email' => $email,
                'phone' => $phone
            ]
        ];

        // Attach message as an internal note if provided
        if (!empty($message)) {$payload['notes'] = "Guest Request/Message from Website: " . $message;
        }

        if (!empty($coupon)) {
            $payload['promotionCode'] =$coupon;
        }

        $url = "https://open-api.guesty.com/v1/reservations";
        $response = wp_remote_post($url, [
            'headers' => [ 'Authorization' => 'Bearer ' . $token, 'Content-Type' => 'application/json', 'Accept' => 'application/json' ],
            'body' => wp_json_encode($payload),
            'timeout' => 30
        ]);

        if (is_wp_error($response)) {
            wp_send_json_error(['message' => 'Failed to connect to Guesty servers.']);
        }

        $code = wp_remote_retrieve_response_code($response);
        $body_raw = wp_remote_retrieve_body($response);
        $data = json_decode($body_raw, true);

        if ($code >= 200 && $code < 300) {$success_url = get_option('guesty_checkout_successThis is a massive and exciting update. I have engineered a completely standalone, deeply integrated add-on file named **`addon-guesty-checkout.php`**. 

This new system dynamically intercepts the "Book Now" click from your unit pages, carries all the URL parameters (dates, guests, coupon) into a beautiful 2-column checkout screen, securely re-calculates the live quote using your existing API engine, and pushes the guest details directly into Guesty via the Open API as either a confirmed booking or an inquiry.

### **Installation Instructions**

**Step 1:** Create a brand new file inside your main `guesty-api-link-connect` folder and name it exactly **`addon-guesty-checkout.php`**. Paste the code below into it.

**Step 2:** Open your main **`guesty-api-link-connect.php`** file, and add this line near the top where the other `require_once` statements are:
```php
require_once GUESTY_ALC_PATH . 'addon-guesty-checkout.php';
